name: Limit Open PRs

on: 
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

jobs:
  limit_prs:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'hacktoberfest-accepted') }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Check open pull requests
      id: get_pr_count
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const openPRraw = await github.rest.pulls.list({
            owner: 'edm00se',
            repo: 'awesome-board-games',
            state: 'open',
            author: context.payload.sender.login,
          });
          const openPRs = openPRraw.data.filter(el => el.user.login === context.payload.sender.login);
          // console.log(openPRs);
          return openPRs.length;
    - name: Under Threshold
      if: ${{ steps.get_pr_count.outputs.result <= 5 }}
      run: "echo User has '${{ steps.get_pr_count.outputs.result }}' counted PRs, including this one. g2g"
    - name: Fail if too many open PRs
      if: ${{ steps.get_pr_count.outputs.result > 5 }}
      uses: actions/github-script@v6
      with:
        script: |
          const prCount = parseInt(${{ steps.get_pr_count.outputs.result }},10);
          const message = `You already have ${prCount-1} other open pull requests. Please focus on completing those before opening new ones. Do not open additional PRs until those are resolved.`;
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
          core.setFailed(message);
