name: Awesome-Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
         uses: actions/checkout@v4
        
        - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 22
           cache: 'npm'
        
        - name: Cache npm dependencies
         id: cache-npm
         uses: actions/cache@v3
         with:
           path: ~/.npm
           key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
           restore-keys: |
             ${{ runner.os }}-npm-
        
        - name: Install dependencies and run build/tests
         run: |
           npm ci
           npm run test
