name: WIP
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  WIP:
    runs-on: ubuntu-latest
    steps:
      - name: Work In Progress Check
        uses: wow-actions/wip@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'do-not-merge', 'work in progress', 'wip', 'needs work', '🚧'